# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iEMOH4qSeS32gSCiLqeFA2sA-NYSKxJJ
"""

from google.colab import drive
drive.mount ('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings

# %matplotlib inline


pd.set_option("display.max_rows", None,"display.max_columns", None)
warnings.simplefilter(action='ignore')
plt.style.use('seaborn')
dataset = pd.DataFrame(pd.read_csv('/content/drive/MyDrive/Dataset ML/student-mat.csv'))

dataset.head()
dataset.info()

dataset.head()
dataset.shape
dataset.info()
dataset.describe()
dataset.isna().sum()
dataset.describe()

dataset.dup = dataset.copy()
dataset.dup.drop_duplicates(subset=None, inplace=True)



for col in dataset:
    print(dataset[col].value_counts(ascending=False), '\n\n\n')

dataset.info()



from sklearn.model_selection import train_test_split

np.random.seed(0)
df_train, df_test = train_test_split(dataset, train_size = 0.80, test_size = 0.20, random_state = 112)
df_train.info()
df_test.info()

df_train.columns

datasetnew = df_train[['school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3']]

plt.show()

from sklearn.metrics import max_error
from sklearn.metrics import r2
from sklearn.metrics import neg_mean_absolute_error
from sklearn.metrics import neg_mean_squared_error